import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';

export default function SignUp(){const c=useColors(),insets=useSafeAreaInsets(),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState('');const submit=()=>{if(!name||!email||!password||password!==confirm){setError('Enter your details and matching passwords.');return}router.replace('/(tabs)')};return <ScrollView style={{backgroundColor:c.background}} contentContainerStyle={[styles.screen,{paddingTop:insets.top+20,paddingBottom:insets.bottom+26}]}><Pressable onPress={()=>router.back()}><Feather name="chevron-left" color={c.gold} size={29}/></Pressable><View style={styles.brand}><Feather name="music" size={31} color={c.gold}/><Text style={[styles.brandName,{color:c.foreground}]}>Play<Text style={{color:c.gold}}>Tune</Text></Text><Text style={[styles.tag,{color:c.mutedForeground}]}>Your music. <Text style={{color:c.gold}}>Your way.</Text></Text></View><Text style={[styles.title,{color:c.foreground}]}>Create Account</Text><Text style={[styles.sub,{color:c.mutedForeground}]}>Sign up to start listening to your music.</Text><View style={styles.form}><Input c={c} value={name} onChangeText={setName} placeholder="Enter your full name" icon="user"/><Input c={c} value={email} onChangeText={setEmail} placeholder="Enter your email address" icon="mail" keyboardType="email-address"/><Input c={c} value={password} onChangeText={setPassword} placeholder="Create a password" icon="lock" secureTextEntry/><Input c={c} value={confirm} onChangeText={setConfirm} placeholder="Confirm your password" icon="lock" secureTextEntry/>{Boolean(error)&&<Text style={{color:c.destructive,fontSize:11}}>{error}</Text>}<Text style={[styles.terms,{color:c.mutedForeground}]}>● I agree to the <Text style={{color:c.gold}}>Terms of Use</Text> and <Text style={{color:c.gold}}>Privacy Policy</Text></Text><Pressable onPress={submit} style={[styles.primary,{backgroundColor:c.gold}]}><Text style={styles.primaryText}>Sign Up</Text></Pressable><Text style={[styles.or,{color:c.mutedForeground}]}>or continue with</Text><Social c={c} icon="google" label="Continue with Google"/><Social c={c} icon="apple" label="Continue with Apple"/><Text style={[styles.login,{color:c.mutedForeground}]}>Already have an account? <Text onPress={()=>router.replace('/login')} style={{color:c.gold}}>Log in</Text></Text></View></ScrollView>}
function Input({c,icon,...props}:any){return <View style={[styles.input,{borderColor:c.border,backgroundColor:c.input}]}><Feather name={icon} size={20} color={c.gold}/><TextInput {...props} placeholderTextColor={c.mutedForeground} style={[styles.field,{color:c.foreground}]}/></View>};function Social({c,icon,label}:{c:any;icon:'google'|'apple';label:string}){return <Pressable style={[styles.social,{borderColor:c.border}]}><Text style={[styles.socialMark,{color:c.gold}]}>{icon==='google'?'G':'●'}</Text><Text style={[styles.socialText,{color:c.foreground}]}>{label}</Text></Pressable>};const styles=StyleSheet.create({screen:{paddingHorizontal:25},brand:{alignItems:'center',marginTop:12},brandName:{fontFamily:'Inter_700Bold',fontSize:29,marginTop:7},tag:{fontFamily:'Inter_400Regular',fontSize:13,marginTop:3},title:{fontFamily:'Inter_700Bold',fontSize:27,marginTop:34},sub:{fontFamily:'Inter_400Regular',fontSize:13,marginTop:7},form:{gap:13,marginTop:25},input:{height:58,borderRadius:13,borderWidth:1,flexDirection:'row',alignItems:'center',paddingHorizontal:17,gap:13},field:{flex:1,fontSize:14,fontFamily:'Inter_400Regular'},terms:{fontFamily:'Inter_400Regular',fontSize:11,lineHeight:17},primary:{height:54,borderRadius:14,alignItems:'center',justifyContent:'center'},primaryText:{fontFamily:'Inter_700Bold',fontSize:16,color:'#17120b'},or:{textAlign:'center',fontFamily:'Inter_400Regular',fontSize:11,marginVertical:3},social:{height:51,borderRadius:13,borderWidth:1,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:12},socialMark:{fontFamily:'Inter_700Bold',fontSize:20},socialText:{fontFamily:'Inter_600SemiBold',fontSize:13},login:{textAlign:'center',fontFamily:'Inter_400Regular',fontSize:12,marginTop:13}});
